debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[traefikLog]
  filePath = "/logs/traefik.log"

[api]
address = ":8080"
    [api.statistics]
    recentErrors = 20  

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
     entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/local.intergo.co/fullchain.pem"
      keyFile = "/ssl/local.intergo.co/privkey.pem"    

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local.intergo.co"
watch = true
exposedByDefault = false
swarmMode = false
